/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : DA1.H
**     Project   : PmsmFocDrv
**     Processor : MC56F8257
**     Component : DAC
**     Version   : Component 01.077, Driver 01.06, CPU db: 3.00.231
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2013-10-1, ÏÂÎç 09:17
**     Abstract  :
**         This bean "DAC" implements an internal D/A converter
**         of the MCU. It allows select channels of D/A converter and
**         contains methods for converting various format of a value to
**         supported format of the D/A converter.
**
**     Settings  :
**         D/A device                  : DAC
**         D/A Channels
**           Pin name                  : GPIOC5_DACO_XB_IN7
**           Pin signal name           : 
**           Init value                : 2048
**         D/A resolution              : converted
**         Data Mode                   : Right justified
**         Glitch filter               : Disabled
**         Synchronous mode            : Disabled
**         Auto. waveform gen.         : Disabled
**         Initialization
**           Enable in init.           : yes
**
**     Contents  :
**         SetValue - byte DA1_SetValue(void* Values);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __DA1
#define __DA1

/* MODULE DA1. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */

#include "Cpu.h"




byte DA1_SetValue(void* Values);
/*
** ===================================================================
**     Method      :  DA1_SetValue (component DAC)
**
**     Description :
**         This method sets values of all channels.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Values          - Pointer to array that contains
**                           the data. Data type is byte, word or int.
**                           It depends on supported modes,
**                           resolution, etc. of the D/A converter.
**                           See version specific information for the
**                           current CPU in <General Info>.
**     Returns     :
**         ---             - Error code, possible codes: 
**                           - ERR_OK - OK
** ===================================================================
*/

void DA1_Init(void);
/*
** ===================================================================
**     Method      :  DA1_Init (component DAC)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

/* END DA1. */

#endif
/* ifndef __DA1 */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
