/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : eFPWM1.C
**     Project   : PmsmFocDrv
**     Processor : MC56F8257
**     Component : Init_eFlexPWM
**     Version   : Component 01.013, Driver 01.00, CPU db: 3.00.231
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2014/4/25, 9:32
**     Abstract  :
**          This file implements the eFlexPWM (eFlexPWM) module initialization
**          according to the Peripheral Initialization Bean settings, and defines
**          interrupt service routines prototypes.
**     Settings  :
**          Component name                                 : eFPWM1
**          Device                                         : eFlexPWM
**          Settings                                       : 
**            Submodule 0                                  : Enabled
**              Submodule 0 device                         : eFlexPWM_SM0
**              Clock setting                              : 
**                PWM clock source                         : IP Bus clock
**                PWM generator clock                      : Enabled
**                PWM prescaler                            : 1
**                Init counter value                       : EC8C
**                PWM value 0 - half cycle point           : 0000
**                PWM value 1 - counter modulo             : 1373
**                Fractional value 1 circuit               : Disabled
**                Fractional value 1                       : 0
**                Dead time value 0                        : 0A8
**                Dead time value 1                        : 0A8
**                PWM frequency                            : 6.024096385542 kHz
**                PWM period                               : 166000 ns
**                PWM dead time 0                          : 2.8 us
**                PWM dead time 1                          : 2.8 us
**              Enabled in Wait mode                       : no
**              Enabled in Debug mode                      : no
**              Channel settings                           : 
**                Mode of PWM ch A and B                   : Complementary
**                Complementary PWM source                 : PWM23
**                Double switching                         : Disabled
**                Channel A (PWM23)                        : 
**                  PWM function                           : 
**                    PWM value 2                          : 0000
**                    Fractional value 2 circuit           : Disabled
**                    Fractional value 2                   : 0
**                    PWM value 3                          : 0000
**                    Fractional value 3 circuit           : Disabled
**                    Fractional value 3                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Force to 0 prior to output polarity
**                    Output polarity                      : Inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Disable by fault 0                   : yes
**                    Disable by fault 1                   : no
**                    Disable by fault 2                   : no
**                    Disable by fault 3                   : no
**                Channel B (PWM45)                        : 
**                  PWM function                           : 
**                    PWM value 4                          : ECC8
**                    Fractional value 4 circuit           : Disabled
**                    Fractional value 4                   : 0
**                    PWM value 5                          : 0000
**                    Fractional value 5 circuit           : Disabled
**                    Fractional value 5                   : 0
**                    SW output                            : Logic 1
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Force to 0 prior to output polarity
**                    Output polarity                      : Inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Disable by fault 0                   : yes
**                    Disable by fault 1                   : no
**                    Disable by fault 2                   : no
**                    Disable by fault 3                   : no
**                Channel X (PWM01)                        : 
**                  PWM function                           : 
**                    Output fault state                   : Force to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Disable by fault 0                   : yes
**                    Disable by fault 1                   : yes
**                    Disable by fault 2                   : yes
**                    Disable by fault 3                   : yes
**              Output trigger settings                    : 
**                OUT_TRIG0 signal settings                : 
**                  Output trigger for Val 0               : Disabled
**                  Output trigger for Val 2               : Disabled
**                  Output trigger for Val 4               : Enabled
**                OUT_TRIG1 signal settings                : 
**                  Output trigger for Val 1               : Disabled
**                  Output trigger for Val 3               : Disabled
**                  Output trigger for Val 5               : Disabled
**              Reload settings                            : 
**                Reload source                            : Local reload signal
**                Reload frequency                         : 1
**                Half cycle reload                        : Disabled
**                Full cycle reload                        : Enabled
**                Load mode                                : Load at next PWM reload if LDOK is set
**              Force and initialization settings          : 
**                Initialization source                    : Local sync signal
**                Force initialization                     : Disabled
**                Force source                             : Local force signal
**                Init value ch A                          : Low
**                Init value ch B                          : Low
**                Init value ch X                          : Low
**            Submodule 1                                  : Enabled
**              Submodule 1 device                         : eFlexPWM_SM1
**              Clock setting                              : 
**                PWM clock source                         : Submodule 0's clock
**                PWM generator clock                      : Enabled
**                PWM prescaler                            : 1
**                Init counter value                       : EC8C
**                PWM value 0 - half cycle point           : 0000
**                PWM value 1 - counter modulo             : 1373
**                Fractional value 1 circuit               : Disabled
**                Fractional value 1                       : 0
**                Dead time value 0                        : 0A8
**                Dead time value 1                        : 0A8
**                PWM frequency                            : 6.024096385542 kHz
**                PWM period                               : 166000 ns
**                PWM dead time 0                          : 2.8 us
**                PWM dead time 1                          : 2.8 us
**              Enabled in Wait mode                       : no
**              Enabled in Debug mode                      : no
**              Channel settings                           : 
**                Mode of PWM ch A and B                   : Complementary
**                Complementary PWM source                 : PWM23
**                Double switching                         : Disabled
**                Channel A (PWM23)                        : 
**                  PWM function                           : 
**                    PWM value 2                          : 0000
**                    Fractional value 2 circuit           : Disabled
**                    Fractional value 2                   : 0
**                    PWM value 3                          : 0000
**                    Fractional value 3 circuit           : Disabled
**                    Fractional value 3                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Force to 0 prior to output polarity
**                    Output polarity                      : Inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Disable by fault 0                   : yes
**                    Disable by fault 1                   : no
**                    Disable by fault 2                   : no
**                    Disable by fault 3                   : no
**                Channel B (PWM45)                        : 
**                  PWM function                           : 
**                    PWM value 4                          : 0000
**                    Fractional value 4 circuit           : Disabled
**                    Fractional value 4                   : 0
**                    PWM value 5                          : 0000
**                    Fractional value 5 circuit           : Disabled
**                    Fractional value 5                   : 0
**                    SW output                            : Logic 1
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Force to 1 prior to output polarity
**                    Output polarity                      : Inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Disable by fault 0                   : yes
**                    Disable by fault 1                   : no
**                    Disable by fault 2                   : no
**                    Disable by fault 3                   : no
**                Channel X (PWM01)                        : 
**                  PWM function                           : 
**                    Output fault state                   : Force to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Disable by fault 0                   : yes
**                    Disable by fault 1                   : yes
**                    Disable by fault 2                   : yes
**                    Disable by fault 3                   : yes
**              Output trigger settings                    : 
**                OUT_TRIG0 signal settings                : 
**                  Output trigger for Val 0               : Disabled
**                  Output trigger for Val 2               : Disabled
**                  Output trigger for Val 4               : Disabled
**                OUT_TRIG1 signal settings                : 
**                  Output trigger for Val 1               : Disabled
**                  Output trigger for Val 3               : Disabled
**                  Output trigger for Val 5               : Disabled
**              Reload settings                            : 
**                Reload source                            : Master reload signal
**                Reload frequency                         : 1
**                Half cycle reload                        : Disabled
**                Full cycle reload                        : Enabled
**                Load mode                                : Load at next PWM reload if LDOK is set
**              Force and initialization settings          : 
**                Initialization source                    : Master sync signal
**                Force initialization                     : Disabled
**                Force source                             : Master force signal
**                Init value ch A                          : Low
**                Init value ch B                          : Low
**                Init value ch X                          : Low
**            Submodule 2                                  : Enabled
**              Submodule 2 device                         : eFlexPWM_SM2
**              Clock setting                              : 
**                PWM clock source                         : Submodule 0's clock
**                PWM generator clock                      : Enabled
**                PWM prescaler                            : 1
**                Init counter value                       : EC8C
**                PWM value 0 - half cycle point           : 0000
**                PWM value 1 - counter modulo             : 1373
**                Fractional value 1 circuit               : Disabled
**                Fractional value 1                       : 0
**                Dead time value 0                        : 0A8
**                Dead time value 1                        : 0A8
**                PWM frequency                            : 6.024096385542 kHz
**                PWM period                               : 166000 ns
**                PWM dead time 0                          : 2.8 us
**                PWM dead time 1                          : 2.8 us
**              Enabled in Wait mode                       : no
**              Enabled in Debug mode                      : no
**              Channel settings                           : 
**                Mode of PWM ch A and B                   : Complementary
**                Complementary PWM source                 : PWM23
**                Double switching                         : Disabled
**                Channel A (PWM23)                        : 
**                  PWM function                           : 
**                    PWM value 2                          : 0000
**                    Fractional value 2 circuit           : Disabled
**                    Fractional value 2                   : 0
**                    PWM value 3                          : 0000
**                    Fractional value 3 circuit           : Disabled
**                    Fractional value 3                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Force to 0 prior to output polarity
**                    Output polarity                      : Inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Disable by fault 0                   : yes
**                    Disable by fault 1                   : no
**                    Disable by fault 2                   : no
**                    Disable by fault 3                   : no
**                Channel B (PWM45)                        : 
**                  PWM function                           : 
**                    PWM value 4                          : 0000
**                    Fractional value 4 circuit           : Disabled
**                    Fractional value 4                   : 0
**                    PWM value 5                          : 0000
**                    Fractional value 5 circuit           : Disabled
**                    Fractional value 5                   : 0
**                    SW output                            : Logic 1
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Force to 0 prior to output polarity
**                    Output polarity                      : Inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Disable by fault 0                   : yes
**                    Disable by fault 1                   : no
**                    Disable by fault 2                   : no
**                    Disable by fault 3                   : no
**                Channel X (PWM01)                        : 
**                  PWM function                           : 
**                    Output fault state                   : Force to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Disable by fault 0                   : yes
**                    Disable by fault 1                   : yes
**                    Disable by fault 2                   : yes
**                    Disable by fault 3                   : yes
**              Output trigger settings                    : 
**                OUT_TRIG0 signal settings                : 
**                  Output trigger for Val 0               : Disabled
**                  Output trigger for Val 2               : Disabled
**                  Output trigger for Val 4               : Disabled
**                OUT_TRIG1 signal settings                : 
**                  Output trigger for Val 1               : Disabled
**                  Output trigger for Val 3               : Disabled
**                  Output trigger for Val 5               : Disabled
**              Reload settings                            : 
**                Reload source                            : Master reload signal
**                Reload frequency                         : 1
**                Half cycle reload                        : Disabled
**                Full cycle reload                        : Enabled
**                Load mode                                : Load at next PWM reload if LDOK is set
**              Force and initialization settings          : 
**                Initialization source                    : Master sync signal
**                Force initialization                     : Disabled
**                Force source                             : Master force signal
**                Init value ch A                          : Low
**                Init value ch B                          : Low
**                Init value ch X                          : Low
**            Submodule 3                                  : Disabled
**            Fault protection settings                    : 
**              Common fault settings                      : 
**                Input filter                             : Enabled
**                  Sample count                           : 7
**                  Sample period                          : 10
**              Fault 0                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Automatic
**                Fault safety mode                        : Normal
**                Fault clearing timing                    : Full cycle only
**              Fault 1                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Fault clearing timing                    : Half or full cycle
**              Fault 2                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Fault clearing timing                    : Half or full cycle
**              Fault 3                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Fault clearing timing                    : Half or full cycle
**          Pins                                           : 
**            SM0 pins                                     : Enabled
**              PWM/Input capture channels                 : 
**                Channel A                                : Enabled
**                  PWM/Input capture pin A                : GPIOE1_PWM0A
**                  Pin A signal                           : 
**                Channel B                                : Enabled
**                  PWM/Input capture pin B                : GPIOE0_PWM0B
**                  Pin B signal                           : 
**                Channel X                                : Disabled
**              External control A - EXTA                  : Disabled
**              External control B - EXTB                  : Disabled
**              External synchronization                   : Disabled
**            SM1 pins                                     : Enabled
**              PWM/Input capture channels                 : 
**                Channel A                                : Enabled
**                  PWM/Input capture pin A                : GPIOE3_PWM1A
**                  Pin A signal                           : 
**                Channel B                                : Enabled
**                  PWM/Input capture pin B                : GPIOE2_PWM1B
**                  Pin B signal                           : 
**                Channel X                                : Disabled
**              External control A - EXTA                  : Disabled
**              External control B - EXTB                  : Disabled
**              External synchronization                   : Disabled
**            SM2 pins                                     : Enabled
**              PWM/Input capture channels                 : 
**                Channel A                                : Enabled
**                  PWM/Input capture pin A                : GPIOE5_PWM2A_XB_IN3
**                  Pin A signal                           : 
**                Channel B                                : Enabled
**                  PWM/Input capture pin B                : GPIOE4_PWM2B_XB_IN2
**                  Pin B signal                           : 
**                Channel X                                : Disabled
**              External control A - EXTA                  : Disabled
**              External control B - EXTB                  : Disabled
**              External synchronization                   : Disabled
**            SM3 pins                                     : Disabled
**            PWM Faults                                   : 
**              Fault 0                                    : Enabled
**                Fault pin 0                              : GPIOF0_XB_IN6
**                Fault pin 0 signal                       : 
**              Fault 1                                    : Disabled
**              Fault 2                                    : Disabled
**              Fault 3                                    : Disabled
**            External clock                               : Disabled
**            External force                               : Disabled
**          Interrupts/DMA                                 : 
**            SM0 Interrupts/DMA                           : Enabled
**              Compare interrupt                          : 
**                Interrupt                                : INT_PWM_SubModule0_Compare
**                Compare interrupt 0                      : Disabled
**                Compare interrupt 1                      : Disabled
**                Compare interrupt 2                      : Disabled
**                Compare interrupt 3                      : Disabled
**                Compare interrupt 4                      : Disabled
**                Compare interrupt 5                      : Disabled
**                Interrupt priority                       : medium priority
**                ISR name                                 : 
**              Reload interrupt                           : 
**                Interrupt                                : INT_PWM_SubModule0_Reload
**                Reload interrupt                         : Enabled
**                Interrupt priority                       : 1
**                ISR name                                 : PWMC1_InterruptOnReload
**            SM1 Interrupts/DMA                           : Disabled
**            SM2 Interrupts/DMA                           : Disabled
**            SM3 Interrupts/DMA                           : Disabled
**            Fault interrupt                              : 
**              Interrupt                                  : INT_PWM_Fault
**              Fault 0 interrupt                          : Enabled
**              Fault 1 interrupt                          : Disabled
**              Fault 2 interrupt                          : Disabled
**              Fault 3 interrupt                          : Disabled
**              Interrupt priority                         : 2
**              ISR name                                   : PWMC1_InterruptOnFault
**            Reload error interrupt                       : 
**              Interrupt                                  : INT_PWM_ReloadError
**              SM0 reload error interrupt                 : Disabled
**              SM1 reload error interrupt                 : Disabled
**              SM2 reload error interrupt                 : Disabled
**              SM3 reload error interrupt                 : Disabled
**              Interrupt priority                         : medium priority
**              ISR name                                   : 
**          Initialization                                 : 
**            Call Init method                             : no
**            Load values after init into SM0              : yes
**            Load values after init into SM1              : yes
**            Load values after init into SM2              : yes
**            Load values after init into SM3              : no
**            Fault test                                   : No simulated fault
**            Monitor PLL mode                             : Do not monitor PLL
**     Contents  :
**         Init - void eFPWM1_Init(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE eFPWM1. */

#include "eFPWM1.h"


/*
** ###################################################################
**
**  The following method(s) must be implemented by the user in one
**  of the following modules:
**
**    #if defined(PWMC1_InterruptOnReload_FAST_INT)
**    #pragma interrupt fast
**    #elif defined(PWMC1_InterruptOnReload_VECT_TABLE_ISR_FAST_INT)
**    #pragma define_section interrupt_fast "interrupt_fast.text"  RX
**    #pragma section interrupt_fast begin
**    #pragma interrupt fast
**    #else
**    #pragma interrupt
**    #endif
**    void PWMC1_InterruptOnReload(void)
**    {
**      // Your interrupt code
**    }
**    #if defined(PWMC1_InterruptOnReload_VECT_TABLE_ISR_FAST_INT)
**    #pragma section interrupt_fast end
**    #endif
**
**    #if defined(PWMC1_InterruptOnFault_FAST_INT)
**    #pragma interrupt fast
**    #elif defined(PWMC1_InterruptOnFault_VECT_TABLE_ISR_FAST_INT)
**    #pragma define_section interrupt_fast "interrupt_fast.text"  RX
**    #pragma section interrupt_fast begin
**    #pragma interrupt fast
**    #else
**    #pragma interrupt
**    #endif
**    void PWMC1_InterruptOnFault(void)
**    {
**      // Your interrupt code
**    }
**    #if defined(PWMC1_InterruptOnFault_VECT_TABLE_ISR_FAST_INT)
**    #pragma section interrupt_fast end
**    #endif
**
**  Modules:
**       PmsmFocDrv
**       CpuIsr
**       PwmMcIsr
**       HallIsr
**       TI_var
**       hallVarDef
**       User_Functions
**       User_FunctionProtypes
**       User_Const
**       User_Types
**       User_Header
**
** ###################################################################
*/

/*
** ===================================================================
**     Method      :  eFPWM1_Init (component Init_eFlexPWM)
**
**     Description :
**         This method initializes registers of the eFlexPWM module
**         according to this Peripheral Initialization settings. 
**         Call this method in the user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the component for more
**         details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void eFPWM1_Init(void)
{
  /* PWM_SM0_OCTRL: PWMA_IN=0,PWMB_IN=0,PWMX_IN=0,??=0,??=0,POLA=1,POLB=1,POLX=0,??=0,??=0,PWMAFS=0,PWMBFS=0,PWMXFS=0 */
  setReg16(PWM_SM0_OCTRL, 0x0600U);    /* Set Output control register */ 
  /* PWM_SM0_INIT: INIT=0xEC8C */
  setReg16(PWM_SM0_INIT, 0xEC8CU);     /* Set Initial count register */ 
  /* PWM_SM0_CTRL2: DBGEN=0,WAITEN=0,INDEP=0,PWM23_INIT=0,PWM45_INIT=0,PWMX_INIT=0,INIT_SEL=0,FRCEN=0,FORCE=0,FORCE_SEL=0,RELOAD_SEL=0,CLK_SEL=0 */
  setReg16(PWM_SM0_CTRL2, 0x00U);      /* Set Control 2 register */ 
  /* PWM_SM0_CTRL: LDFQ=0,HALF=0,FULL=1,DT=0,??=0,PRSC=0,??=0,LDMOD=0,??=0,DBLEN=0 */
  setReg16(PWM_SM0_CTRL, 0x0400U);     /* Set Control register */ 
  /* PWM_SM0_TCTRL: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,OUT_TRIG_EN=0x10 */
  setReg16(PWM_SM0_TCTRL, 0x10U);      /* Set Output trigger control register */ 
  /* PWM_SM0_VAL0: VAL0=0 */
  setReg16(PWM_SM0_VAL0, 0x00U);       /* Set Value 0 register */ 
  /* PWM_SM0_VAL1: VAL1=0x1373 */
  setReg16(PWM_SM0_VAL1, 0x1373U);     /* Set Value 1 register */ 
  /* PWM_SM0_VAL2: VAL2=0 */
  setReg16(PWM_SM0_VAL2, 0x00U);       /* Set Value 2 register */ 
  /* PWM_SM0_VAL3: VAL3=0 */
  setReg16(PWM_SM0_VAL3, 0x00U);       /* Set Value 3 register */ 
  /* PWM_SM0_VAL4: VAL4=0xECC8 */
  setReg16(PWM_SM0_VAL4, 0xECC8U);     /* Set Value 4 register */ 
  /* PWM_SM0_VAL5: VAL5=0 */
  setReg16(PWM_SM0_VAL5, 0x00U);       /* Set Value 5 register */ 
  /* PWM_SM0_FRACVAL1: FRACVAL1=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM0_FRACVAL1, 0x00U);   /* Set Fractional value 1 register */ 
  /* PWM_SM0_FRACVAL2: FRACVAL2=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM0_FRACVAL2, 0x00U);   /* Set Fractional value 2 register */ 
  /* PWM_SM0_FRACVAL3: FRACVAL3=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM0_FRACVAL3, 0x00U);   /* Set Fractional value 3 register */ 
  /* PWM_SM0_FRACVAL4: FRACVAL4=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM0_FRACVAL4, 0x00U);   /* Set Fractional value 4 register */ 
  /* PWM_SM0_FRACVAL5: FRACVAL5=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM0_FRACVAL5, 0x00U);   /* Set Fractional value 5 register */ 
  /* PWM_SM0_FRCTRL: TEST=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,FRAC5_EN=0,FRAC4_EN=0,FRAC3_EN=0,FRAC2_EN=0,FRAC1_EN=0,??=0 */
  setReg16(PWM_SM0_FRCTRL, 0x00U);     /* Set Fractional control register */ 
  /* PWM_SM0_DISMAP: ??=0,??=0,??=0,??=0,DISX=0x0F,DISB=1,DISA=1 */
  setReg16(PWM_SM0_DISMAP, 0x0F11U);   /* Set Fault disable mapping register */ 
  /* PWM_SM0_DTCNT0: ??=0,??=0,??=0,??=0,??=0,DTCNT0=0xA8 */
  setReg16(PWM_SM0_DTCNT0, 0xA8U);     /* Set Deadtime count 0 register */ 
  /* PWM_SM0_DTCNT1: ??=0,??=0,??=0,??=0,??=0,DTCNT1=0xA8 */
  setReg16(PWM_SM0_DTCNT1, 0xA8U);     /* Set Deadtime count 1 register */ 
  /* PWM_SM1_OCTRL: PWMA_IN=0,PWMB_IN=0,PWMX_IN=0,??=0,??=0,POLA=1,POLB=1,POLX=0,??=0,??=0,PWMAFS=0,PWMBFS=1,PWMXFS=0 */
  setReg16(PWM_SM1_OCTRL, 0x0604U);    /* Set Output control register */ 
  /* PWM_SM1_INIT: INIT=0xEC8C */
  setReg16(PWM_SM1_INIT, 0xEC8CU);     /* Set Initial count register */ 
  /* PWM_SM1_CTRL2: DBGEN=0,WAITEN=0,INDEP=0,PWM23_INIT=0,PWM45_INIT=0,PWMX_INIT=0,INIT_SEL=2,FRCEN=0,FORCE=0,FORCE_SEL=1,RELOAD_SEL=1,CLK_SEL=2 */
  setReg16(PWM_SM1_CTRL2, 0x020EU);    /* Set Control 2 register */ 
  /* PWM_SM1_CTRL: LDFQ=0,HALF=0,FULL=1,DT=0,??=0,PRSC=0,??=0,LDMOD=0,??=0,DBLEN=0 */
  setReg16(PWM_SM1_CTRL, 0x0400U);     /* Set Control register */ 
  /* PWM_SM1_TCTRL: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,OUT_TRIG_EN=0 */
  setReg16(PWM_SM1_TCTRL, 0x00U);      /* Set Output trigger control register */ 
  /* PWM_SM1_VAL0: VAL0=0 */
  setReg16(PWM_SM1_VAL0, 0x00U);       /* Set Value 0 register */ 
  /* PWM_SM1_VAL1: VAL1=0x1373 */
  setReg16(PWM_SM1_VAL1, 0x1373U);     /* Set Value 1 register */ 
  /* PWM_SM1_VAL2: VAL2=0 */
  setReg16(PWM_SM1_VAL2, 0x00U);       /* Set Value 2 register */ 
  /* PWM_SM1_VAL3: VAL3=0 */
  setReg16(PWM_SM1_VAL3, 0x00U);       /* Set Value 3 register */ 
  /* PWM_SM1_VAL4: VAL4=0 */
  setReg16(PWM_SM1_VAL4, 0x00U);       /* Set Value 4 register */ 
  /* PWM_SM1_VAL5: VAL5=0 */
  setReg16(PWM_SM1_VAL5, 0x00U);       /* Set Value 5 register */ 
  /* PWM_SM1_FRACVAL1: FRACVAL1=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM1_FRACVAL1, 0x00U);   /* Set Fractional value 1 register */ 
  /* PWM_SM1_FRACVAL2: FRACVAL2=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM1_FRACVAL2, 0x00U);   /* Set Fractional value 2 register */ 
  /* PWM_SM1_FRACVAL3: FRACVAL3=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM1_FRACVAL3, 0x00U);   /* Set Fractional value 3 register */ 
  /* PWM_SM1_FRACVAL4: FRACVAL4=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM1_FRACVAL4, 0x00U);   /* Set Fractional value 4 register */ 
  /* PWM_SM1_FRACVAL5: FRACVAL5=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM1_FRACVAL5, 0x00U);   /* Set Fractional value 5 register */ 
  /* PWM_SM1_FRCTRL: TEST=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,FRAC5_EN=0,FRAC4_EN=0,FRAC3_EN=0,FRAC2_EN=0,FRAC1_EN=0,??=0 */
  setReg16(PWM_SM1_FRCTRL, 0x00U);     /* Set Fractional control register */ 
  /* PWM_SM1_DISMAP: ??=0,??=0,??=0,??=0,DISX=0x0F,DISB=1,DISA=1 */
  setReg16(PWM_SM1_DISMAP, 0x0F11U);   /* Set Fault disable mapping register */ 
  /* PWM_SM1_DTCNT0: ??=0,??=0,??=0,??=0,??=0,DTCNT0=0xA8 */
  setReg16(PWM_SM1_DTCNT0, 0xA8U);     /* Set Deadtime count 0 register */ 
  /* PWM_SM1_DTCNT1: ??=0,??=0,??=0,??=0,??=0,DTCNT1=0xA8 */
  setReg16(PWM_SM1_DTCNT1, 0xA8U);     /* Set Deadtime count 1 register */ 
  /* PWM_SM2_OCTRL: PWMA_IN=0,PWMB_IN=0,PWMX_IN=0,??=0,??=0,POLA=1,POLB=1,POLX=0,??=0,??=0,PWMAFS=0,PWMBFS=0,PWMXFS=0 */
  setReg16(PWM_SM2_OCTRL, 0x0600U);    /* Set Output control register */ 
  /* PWM_SM2_INIT: INIT=0xEC8C */
  setReg16(PWM_SM2_INIT, 0xEC8CU);     /* Set Initial count register */ 
  /* PWM_SM2_CTRL2: DBGEN=0,WAITEN=0,INDEP=0,PWM23_INIT=0,PWM45_INIT=0,PWMX_INIT=0,INIT_SEL=2,FRCEN=0,FORCE=0,FORCE_SEL=1,RELOAD_SEL=1,CLK_SEL=2 */
  setReg16(PWM_SM2_CTRL2, 0x020EU);    /* Set Control 2 register */ 
  /* PWM_SM2_CTRL: LDFQ=0,HALF=0,FULL=1,DT=0,??=0,PRSC=0,??=0,LDMOD=0,??=0,DBLEN=0 */
  setReg16(PWM_SM2_CTRL, 0x0400U);     /* Set Control register */ 
  /* PWM_SM2_TCTRL: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,OUT_TRIG_EN=0 */
  setReg16(PWM_SM2_TCTRL, 0x00U);      /* Set Output trigger control register */ 
  /* PWM_SM2_VAL0: VAL0=0 */
  setReg16(PWM_SM2_VAL0, 0x00U);       /* Set Value 0 register */ 
  /* PWM_SM2_VAL1: VAL1=0x1373 */
  setReg16(PWM_SM2_VAL1, 0x1373U);     /* Set Value 1 register */ 
  /* PWM_SM2_VAL2: VAL2=0 */
  setReg16(PWM_SM2_VAL2, 0x00U);       /* Set Value 2 register */ 
  /* PWM_SM2_VAL3: VAL3=0 */
  setReg16(PWM_SM2_VAL3, 0x00U);       /* Set Value 3 register */ 
  /* PWM_SM2_VAL4: VAL4=0 */
  setReg16(PWM_SM2_VAL4, 0x00U);       /* Set Value 4 register */ 
  /* PWM_SM2_VAL5: VAL5=0 */
  setReg16(PWM_SM2_VAL5, 0x00U);       /* Set Value 5 register */ 
  /* PWM_SM2_FRACVAL1: FRACVAL1=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM2_FRACVAL1, 0x00U);   /* Set Fractional value 1 register */ 
  /* PWM_SM2_FRACVAL2: FRACVAL2=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM2_FRACVAL2, 0x00U);   /* Set Fractional value 2 register */ 
  /* PWM_SM2_FRACVAL3: FRACVAL3=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM2_FRACVAL3, 0x00U);   /* Set Fractional value 3 register */ 
  /* PWM_SM2_FRACVAL4: FRACVAL4=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM2_FRACVAL4, 0x00U);   /* Set Fractional value 4 register */ 
  /* PWM_SM2_FRACVAL5: FRACVAL5=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0 */
  setReg16(PWM_SM2_FRACVAL5, 0x00U);   /* Set Fractional value 5 register */ 
  /* PWM_SM2_FRCTRL: TEST=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,FRAC5_EN=0,FRAC4_EN=0,FRAC3_EN=0,FRAC2_EN=0,FRAC1_EN=0,??=0 */
  setReg16(PWM_SM2_FRCTRL, 0x00U);     /* Set Fractional control register */ 
  /* PWM_SM2_DISMAP: ??=0,??=0,??=0,??=0,DISX=0x0F,DISB=1,DISA=1 */
  setReg16(PWM_SM2_DISMAP, 0x0F11U);   /* Set Fault disable mapping register */ 
  /* PWM_SM2_DTCNT0: ??=0,??=0,??=0,??=0,??=0,DTCNT0=0xA8 */
  setReg16(PWM_SM2_DTCNT0, 0xA8U);     /* Set Deadtime count 0 register */ 
  /* PWM_SM2_DTCNT1: ??=0,??=0,??=0,??=0,??=0,DTCNT1=0xA8 */
  setReg16(PWM_SM2_DTCNT1, 0xA8U);     /* Set Deadtime count 1 register */ 
  /* PWM_FFILT: GSTR=0,??=0,??=0,??=0,??=0,FILT_CNT=0,FILT_PER=0x0A */
  setReg16(PWM_FFILT, 0x0AU);          /* Set Fault filter register */ 
  /* PWM_FCTRL: FLVL=0,FAUTO=1,FSAFE=0,FIE=1 */
  setReg16(PWM_FCTRL, 0x0101U);        /* Set Fault control register */ 
  /* PWM_FSTS: ??=0,??=0,??=0,FTEST=0,FFPIN=0x0F,FFULL=1,FFLAG=0x0F */
  setReg16(PWM_FSTS, 0x0F1FU);         /* Set Fault status register */ 
  /* PWM_MASK: ??=0,??=0,??=0,??=0,MASKA=0,MASKB=0,MASKX=0 */
  setReg16(PWM_MASK, 0x00U);           /* Set Output mask register */ 
  /* PWM_SWCOUT: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,SM3OUT23=0,SM3OUT45=0,SM2OUT23=0,SM2OUT45=1,SM1OUT23=0,SM1OUT45=1,SM0OUT23=0,SM0OUT45=1 */
  setReg16(PWM_SWCOUT, 0x15U);         /* Set Software controlled output register */ 
  /* PWM_DTSRCSEL: SM3SEL23=0,SM3SEL45=0,SM2SEL23=0,SM2SEL45=0,SM1SEL23=0,SM1SEL45=0,SM0SEL23=0,SM0SEL45=0 */
  setReg16(PWM_DTSRCSEL, 0x00U);       /* Set Deadtime source select register */ 
  /* PWM_MCTRL2: ??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,??=0,MONPLL=0 */
  setReg16(PWM_MCTRL2, 0x00U);         /* Set Master control 2 register */ 
  /* PWM_OUTEN: ??=0,??=0,??=0,??=0,PWMA_EN=0,PWMB_EN=0,PWMX_EN=0 */
  setReg16(PWM_OUTEN, 0x00U);          /* Set Output enable register */ 
  /* PWM_MCTRL: RUN=0,CLDOK=0,LDOK|=7 */
  clrSetReg16Bits(PWM_MCTRL, 0x0FF0U, 0x07U); /* Set Master control register */ 
  /* PWM_MCTRL: RUN|=7 */
  setReg16Bits(PWM_MCTRL, 0x0700U);    /* Counters' clock enable */ 
  /* PWM_SM0_STS: ??=0,RUF=0,REF=1,RF=1,CFA1=1,CFA0=1,CFB1=1,CFB0=1,CFX1=1,CFX0=1,CMPF=0x3F */
  setReg16(PWM_SM0_STS, 0x3FFFU);      /* Clear interrupt flags */ 
  /* PWM_SM1_STS: ??=0,RUF=0,REF=1,RF=1,CFA1=1,CFA0=1,CFB1=1,CFB0=1,CFX1=1,CFX0=1,CMPF=0x3F */
  setReg16(PWM_SM1_STS, 0x3FFFU);      /* Clear interrupt flags */ 
  /* PWM_SM2_STS: ??=0,RUF=0,REF=1,RF=1,CFA1=1,CFA0=1,CFB1=1,CFB0=1,CFX1=1,CFX0=1,CMPF=0x3F */
  setReg16(PWM_SM2_STS, 0x3FFFU);      /* Clear interrupt flags */ 
  /* PWM_SM0_INTEN: ??=0,??=0,REIE=0,RIE=1,CA1IE=0,CA0IE=0,CB1IE=0,CB0IE=0,CX1IE=0,CX0IE=0,CMPIE=0 */
  setReg16(PWM_SM0_INTEN, 0x1000U);    /* Set Interrupt enable register */ 
  /* PWM_SM1_INTEN: ??=0,??=0,REIE=0,RIE=0,CA1IE=0,CA0IE=0,CB1IE=0,CB0IE=0,CX1IE=0,CX0IE=0,CMPIE=0 */
  setReg16(PWM_SM1_INTEN, 0x00U);      /* Set Interrupt enable register */ 
  /* PWM_SM2_INTEN: ??=0,??=0,REIE=0,RIE=0,CA1IE=0,CA0IE=0,CB1IE=0,CB0IE=0,CX1IE=0,CX0IE=0,CMPIE=0 */
  setReg16(PWM_SM2_INTEN, 0x00U);      /* Set Interrupt enable register */ 
}

/* END eFPWM1. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
