/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : eFPWM1.H
**     Project   : PmsmFocDrv
**     Processor : MC56F8257
**     Component : Init_eFlexPWM
**     Version   : Component 01.013, Driver 01.00, CPU db: 3.00.231
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2014/4/25, 9:32
**     Abstract  :
**          This file implements the eFlexPWM (eFlexPWM) module initialization
**          according to the Peripheral Initialization Bean settings, and defines
**          interrupt service routines prototypes.
**     Settings  :
**          Component name                                 : eFPWM1
**          Device                                         : eFlexPWM
**          Settings                                       : 
**            Submodule 0                                  : Enabled
**              Submodule 0 device                         : eFlexPWM_SM0
**              Clock setting                              : 
**                PWM clock source                         : IP Bus clock
**                PWM generator clock                      : Enabled
**                PWM prescaler                            : 1
**                Init counter value                       : EC8C
**                PWM value 0 - half cycle point           : 0000
**                PWM value 1 - counter modulo             : 1373
**                Fractional value 1 circuit               : Disabled
**                Fractional value 1                       : 0
**                Dead time value 0                        : 0A8
**                Dead time value 1                        : 0A8
**                PWM frequency                            : 6.024096385542 kHz
**                PWM period                               : 166000 ns
**                PWM dead time 0                          : 2.8 us
**                PWM dead time 1                          : 2.8 us
**              Enabled in Wait mode                       : no
**              Enabled in Debug mode                      : no
**              Channel settings                           : 
**                Mode of PWM ch A and B                   : Complementary
**                Complementary PWM source                 : PWM23
**                Double switching                         : Disabled
**                Channel A (PWM23)                        : 
**                  PWM function                           : 
**                    PWM value 2                          : 0000
**                    Fractional value 2 circuit           : Disabled
**                    Fractional value 2                   : 0
**                    PWM value 3                          : 0000
**                    Fractional value 3 circuit           : Disabled
**                    Fractional value 3                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Force to 0 prior to output polarity
**                    Output polarity                      : Inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Disable by fault 0                   : yes
**                    Disable by fault 1                   : no
**                    Disable by fault 2                   : no
**                    Disable by fault 3                   : no
**                Channel B (PWM45)                        : 
**                  PWM function                           : 
**                    PWM value 4                          : ECC8
**                    Fractional value 4 circuit           : Disabled
**                    Fractional value 4                   : 0
**                    PWM value 5                          : 0000
**                    Fractional value 5 circuit           : Disabled
**                    Fractional value 5                   : 0
**                    SW output                            : Logic 1
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Force to 0 prior to output polarity
**                    Output polarity                      : Inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Disable by fault 0                   : yes
**                    Disable by fault 1                   : no
**                    Disable by fault 2                   : no
**                    Disable by fault 3                   : no
**                Channel X (PWM01)                        : 
**                  PWM function                           : 
**                    Output fault state                   : Force to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Disable by fault 0                   : yes
**                    Disable by fault 1                   : yes
**                    Disable by fault 2                   : yes
**                    Disable by fault 3                   : yes
**              Output trigger settings                    : 
**                OUT_TRIG0 signal settings                : 
**                  Output trigger for Val 0               : Disabled
**                  Output trigger for Val 2               : Disabled
**                  Output trigger for Val 4               : Enabled
**                OUT_TRIG1 signal settings                : 
**                  Output trigger for Val 1               : Disabled
**                  Output trigger for Val 3               : Disabled
**                  Output trigger for Val 5               : Disabled
**              Reload settings                            : 
**                Reload source                            : Local reload signal
**                Reload frequency                         : 1
**                Half cycle reload                        : Disabled
**                Full cycle reload                        : Enabled
**                Load mode                                : Load at next PWM reload if LDOK is set
**              Force and initialization settings          : 
**                Initialization source                    : Local sync signal
**                Force initialization                     : Disabled
**                Force source                             : Local force signal
**                Init value ch A                          : Low
**                Init value ch B                          : Low
**                Init value ch X                          : Low
**            Submodule 1                                  : Enabled
**              Submodule 1 device                         : eFlexPWM_SM1
**              Clock setting                              : 
**                PWM clock source                         : Submodule 0's clock
**                PWM generator clock                      : Enabled
**                PWM prescaler                            : 1
**                Init counter value                       : EC8C
**                PWM value 0 - half cycle point           : 0000
**                PWM value 1 - counter modulo             : 1373
**                Fractional value 1 circuit               : Disabled
**                Fractional value 1                       : 0
**                Dead time value 0                        : 0A8
**                Dead time value 1                        : 0A8
**                PWM frequency                            : 6.024096385542 kHz
**                PWM period                               : 166000 ns
**                PWM dead time 0                          : 2.8 us
**                PWM dead time 1                          : 2.8 us
**              Enabled in Wait mode                       : no
**              Enabled in Debug mode                      : no
**              Channel settings                           : 
**                Mode of PWM ch A and B                   : Complementary
**                Complementary PWM source                 : PWM23
**                Double switching                         : Disabled
**                Channel A (PWM23)                        : 
**                  PWM function                           : 
**                    PWM value 2                          : 0000
**                    Fractional value 2 circuit           : Disabled
**                    Fractional value 2                   : 0
**                    PWM value 3                          : 0000
**                    Fractional value 3 circuit           : Disabled
**                    Fractional value 3                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Force to 0 prior to output polarity
**                    Output polarity                      : Inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Disable by fault 0                   : yes
**                    Disable by fault 1                   : no
**                    Disable by fault 2                   : no
**                    Disable by fault 3                   : no
**                Channel B (PWM45)                        : 
**                  PWM function                           : 
**                    PWM value 4                          : 0000
**                    Fractional value 4 circuit           : Disabled
**                    Fractional value 4                   : 0
**                    PWM value 5                          : 0000
**                    Fractional value 5 circuit           : Disabled
**                    Fractional value 5                   : 0
**                    SW output                            : Logic 1
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Force to 1 prior to output polarity
**                    Output polarity                      : Inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Disable by fault 0                   : yes
**                    Disable by fault 1                   : no
**                    Disable by fault 2                   : no
**                    Disable by fault 3                   : no
**                Channel X (PWM01)                        : 
**                  PWM function                           : 
**                    Output fault state                   : Force to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Disable by fault 0                   : yes
**                    Disable by fault 1                   : yes
**                    Disable by fault 2                   : yes
**                    Disable by fault 3                   : yes
**              Output trigger settings                    : 
**                OUT_TRIG0 signal settings                : 
**                  Output trigger for Val 0               : Disabled
**                  Output trigger for Val 2               : Disabled
**                  Output trigger for Val 4               : Disabled
**                OUT_TRIG1 signal settings                : 
**                  Output trigger for Val 1               : Disabled
**                  Output trigger for Val 3               : Disabled
**                  Output trigger for Val 5               : Disabled
**              Reload settings                            : 
**                Reload source                            : Master reload signal
**                Reload frequency                         : 1
**                Half cycle reload                        : Disabled
**                Full cycle reload                        : Enabled
**                Load mode                                : Load at next PWM reload if LDOK is set
**              Force and initialization settings          : 
**                Initialization source                    : Master sync signal
**                Force initialization                     : Disabled
**                Force source                             : Master force signal
**                Init value ch A                          : Low
**                Init value ch B                          : Low
**                Init value ch X                          : Low
**            Submodule 2                                  : Enabled
**              Submodule 2 device                         : eFlexPWM_SM2
**              Clock setting                              : 
**                PWM clock source                         : Submodule 0's clock
**                PWM generator clock                      : Enabled
**                PWM prescaler                            : 1
**                Init counter value                       : EC8C
**                PWM value 0 - half cycle point           : 0000
**                PWM value 1 - counter modulo             : 1373
**                Fractional value 1 circuit               : Disabled
**                Fractional value 1                       : 0
**                Dead time value 0                        : 0A8
**                Dead time value 1                        : 0A8
**                PWM frequency                            : 6.024096385542 kHz
**                PWM period                               : 166000 ns
**                PWM dead time 0                          : 2.8 us
**                PWM dead time 1                          : 2.8 us
**              Enabled in Wait mode                       : no
**              Enabled in Debug mode                      : no
**              Channel settings                           : 
**                Mode of PWM ch A and B                   : Complementary
**                Complementary PWM source                 : PWM23
**                Double switching                         : Disabled
**                Channel A (PWM23)                        : 
**                  PWM function                           : 
**                    PWM value 2                          : 0000
**                    Fractional value 2 circuit           : Disabled
**                    Fractional value 2                   : 0
**                    PWM value 3                          : 0000
**                    Fractional value 3 circuit           : Disabled
**                    Fractional value 3                   : 0
**                    SW output                            : Logic 0
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Force to 0 prior to output polarity
**                    Output polarity                      : Inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Disable by fault 0                   : yes
**                    Disable by fault 1                   : no
**                    Disable by fault 2                   : no
**                    Disable by fault 3                   : no
**                Channel B (PWM45)                        : 
**                  PWM function                           : 
**                    PWM value 4                          : 0000
**                    Fractional value 4 circuit           : Disabled
**                    Fractional value 4                   : 0
**                    PWM value 5                          : 0000
**                    Fractional value 5 circuit           : Disabled
**                    Fractional value 5                   : 0
**                    SW output                            : Logic 1
**                    Deadtime source                      : Generated PWM
**                    Output fault state                   : Force to 0 prior to output polarity
**                    Output polarity                      : Inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Disable by fault 0                   : yes
**                    Disable by fault 1                   : no
**                    Disable by fault 2                   : no
**                    Disable by fault 3                   : no
**                Channel X (PWM01)                        : 
**                  PWM function                           : 
**                    Output fault state                   : Force to 0 prior to output polarity
**                    Output polarity                      : Not inverted
**                    Channel masked                       : no
**                    Channel output                       : Disabled
**                    Disable by fault 0                   : yes
**                    Disable by fault 1                   : yes
**                    Disable by fault 2                   : yes
**                    Disable by fault 3                   : yes
**              Output trigger settings                    : 
**                OUT_TRIG0 signal settings                : 
**                  Output trigger for Val 0               : Disabled
**                  Output trigger for Val 2               : Disabled
**                  Output trigger for Val 4               : Disabled
**                OUT_TRIG1 signal settings                : 
**                  Output trigger for Val 1               : Disabled
**                  Output trigger for Val 3               : Disabled
**                  Output trigger for Val 5               : Disabled
**              Reload settings                            : 
**                Reload source                            : Master reload signal
**                Reload frequency                         : 1
**                Half cycle reload                        : Disabled
**                Full cycle reload                        : Enabled
**                Load mode                                : Load at next PWM reload if LDOK is set
**              Force and initialization settings          : 
**                Initialization source                    : Master sync signal
**                Force initialization                     : Disabled
**                Force source                             : Master force signal
**                Init value ch A                          : Low
**                Init value ch B                          : Low
**                Init value ch X                          : Low
**            Submodule 3                                  : Disabled
**            Fault protection settings                    : 
**              Common fault settings                      : 
**                Input filter                             : Enabled
**                  Sample count                           : 7
**                  Sample period                          : 10
**              Fault 0                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Automatic
**                Fault safety mode                        : Normal
**                Fault clearing timing                    : Full cycle only
**              Fault 1                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Fault clearing timing                    : Half or full cycle
**              Fault 2                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Fault clearing timing                    : Half or full cycle
**              Fault 3                                    : 
**                Fault active level                       : Logic 0
**                Fault clearing mode                      : Manual
**                Fault safety mode                        : Normal
**                Fault clearing timing                    : Half or full cycle
**          Pins                                           : 
**            SM0 pins                                     : Enabled
**              PWM/Input capture channels                 : 
**                Channel A                                : Enabled
**                  PWM/Input capture pin A                : GPIOE1_PWM0A
**                  Pin A signal                           : 
**                Channel B                                : Enabled
**                  PWM/Input capture pin B                : GPIOE0_PWM0B
**                  Pin B signal                           : 
**                Channel X                                : Disabled
**              External control A - EXTA                  : Disabled
**              External control B - EXTB                  : Disabled
**              External synchronization                   : Disabled
**            SM1 pins                                     : Enabled
**              PWM/Input capture channels                 : 
**                Channel A                                : Enabled
**                  PWM/Input capture pin A                : GPIOE3_PWM1A
**                  Pin A signal                           : 
**                Channel B                                : Enabled
**                  PWM/Input capture pin B                : GPIOE2_PWM1B
**                  Pin B signal                           : 
**                Channel X                                : Disabled
**              External control A - EXTA                  : Disabled
**              External control B - EXTB                  : Disabled
**              External synchronization                   : Disabled
**            SM2 pins                                     : Enabled
**              PWM/Input capture channels                 : 
**                Channel A                                : Enabled
**                  PWM/Input capture pin A                : GPIOE5_PWM2A_XB_IN3
**                  Pin A signal                           : 
**                Channel B                                : Enabled
**                  PWM/Input capture pin B                : GPIOE4_PWM2B_XB_IN2
**                  Pin B signal                           : 
**                Channel X                                : Disabled
**              External control A - EXTA                  : Disabled
**              External control B - EXTB                  : Disabled
**              External synchronization                   : Disabled
**            SM3 pins                                     : Disabled
**            PWM Faults                                   : 
**              Fault 0                                    : Enabled
**                Fault pin 0                              : GPIOF0_XB_IN6
**                Fault pin 0 signal                       : 
**              Fault 1                                    : Disabled
**              Fault 2                                    : Disabled
**              Fault 3                                    : Disabled
**            External clock                               : Disabled
**            External force                               : Disabled
**          Interrupts/DMA                                 : 
**            SM0 Interrupts/DMA                           : Enabled
**              Compare interrupt                          : 
**                Interrupt                                : INT_PWM_SubModule0_Compare
**                Compare interrupt 0                      : Disabled
**                Compare interrupt 1                      : Disabled
**                Compare interrupt 2                      : Disabled
**                Compare interrupt 3                      : Disabled
**                Compare interrupt 4                      : Disabled
**                Compare interrupt 5                      : Disabled
**                Interrupt priority                       : medium priority
**                ISR name                                 : 
**              Reload interrupt                           : 
**                Interrupt                                : INT_PWM_SubModule0_Reload
**                Reload interrupt                         : Enabled
**                Interrupt priority                       : 1
**                ISR name                                 : PWMC1_InterruptOnReload
**            SM1 Interrupts/DMA                           : Disabled
**            SM2 Interrupts/DMA                           : Disabled
**            SM3 Interrupts/DMA                           : Disabled
**            Fault interrupt                              : 
**              Interrupt                                  : INT_PWM_Fault
**              Fault 0 interrupt                          : Enabled
**              Fault 1 interrupt                          : Disabled
**              Fault 2 interrupt                          : Disabled
**              Fault 3 interrupt                          : Disabled
**              Interrupt priority                         : 2
**              ISR name                                   : PWMC1_InterruptOnFault
**            Reload error interrupt                       : 
**              Interrupt                                  : INT_PWM_ReloadError
**              SM0 reload error interrupt                 : Disabled
**              SM1 reload error interrupt                 : Disabled
**              SM2 reload error interrupt                 : Disabled
**              SM3 reload error interrupt                 : Disabled
**              Interrupt priority                         : medium priority
**              ISR name                                   : 
**          Initialization                                 : 
**            Call Init method                             : no
**            Load values after init into SM0              : yes
**            Load values after init into SM1              : yes
**            Load values after init into SM2              : yes
**            Load values after init into SM3              : no
**            Fault test                                   : No simulated fault
**            Monitor PLL mode                             : Do not monitor PLL
**     Contents  :
**         Init - void eFPWM1_Init(void);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __eFPWM1_H
#define __eFPWM1_H

/* MODULE eFPWM1. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */

#include "Cpu.h"




/* PESL device mapping  */
#define eFPWM1_DEVICE eFlexPWM

extern void PWMC1_InterruptOnReload(void);
extern void PWMC1_InterruptOnFault(void);

void eFPWM1_Init(void);
/*
** ===================================================================
**     Method      :  eFPWM1_Init (component Init_eFlexPWM)
**
**     Description :
**         This method initializes registers of the eFlexPWM module
**         according to this Peripheral Initialization settings. 
**         Call this method in the user code to initialize the module.
**         By default, the method is called by PE automatically; see
**         "Call Init method" property of the component for more
**         details.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END eFPWM1. */

#endif
/* ifndef __eFPWM1_H */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
