/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : HallTmr.C
**     Project   : PmsmFocDrv
**     Processor : MC56F8257
**     Component : FreeCntr
**     Version   : Component 01.112, Driver 02.04, CPU db: 3.00.231
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 2014/4/25, 9:32
**     Abstract  :
**         This device "FreeCntr" implements a free running counter for
**         time measurement.
**     Settings  :
**         Timer name                  : TMRA01 (32-bit)
**         Counter shared              : No
**
**         High speed mode
**             Prescaler               : divide-by-1
**             Clock                   : 60000000 Hz
**           Period
**             Xtal ticks              : 572662306
**             microseconds            : 71582788
**             milliseconds            : 71583
**             seconds                 : 72
**             seconds (real)          : 71.582788266667
**           Frequency of counting (Bus clock / prescaler)
**             Hz                      : 60000000
**
**         Initialization:
**              Timer                  : Enabled
**
**         Timer registers
**              Counter                : TMRA1_CNTR [F015]
**              Mode                   : TMRA1_CTRL [F016]
**              Run                    : TMRA1_CTRL [F016]
**              Prescaler              : TMRA1_CTRL [F016]
**
**         User handling procedure     : not specified
**     Contents  :
**         Reset           - byte HallTmr_Reset(void);
**         GetCounterValue - byte HallTmr_GetCounterValue(HallTmr_TTimerValue *Value);
**
**     Copyright : 1997 - 2009 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE HallTmr. */

#include "HallTmr.h"


/* Internal method prototypes */
static void SetPV(byte Val);

/*
** ===================================================================
**     Method      :  SetPV (component FreeCntr)
**
**     Description :
**         Sets prescaler value. The method is called automatically as a 
**         part of several internal methods.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void SetPV(byte Val)
{
  EnterCritical();                     /* Disable global interrupts */
  setRegBitGroup(TMRA0_CTRL,PCS,Val);  /* Store given value to the prescaler */
  setReg(TMRA0_CNTR,0);                /* Reset counter */
  setReg(TMRA1_CNTR,0);
  ExitCritical();                      /* Enable global interrupts */
}

/*
** ===================================================================
**     Method      :  HallTmr_Reset (component FreeCntr)
**
**     Description :
**         This method resets the timer-counter (sets to zero for
**         up-counting HW or to appropriate value for down-counting HW).
**         The method is available only if the counter register can be
**         set by software and the counter is not shared.
**     Parameters  : None
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte HallTmr_Reset(void)
{
  EnterCritical();                     /* Disable global interrupts */
  setReg(TMRA0_CNTR,0x00);             /* Reset counter register */
  setReg(TMRA1_CNTR,0x00);
  ExitCritical();                      /* Enable global interrupts */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  HallTmr_GetCounterValue (component FreeCntr)
**
**     Description :
**         This method returns a content of counter.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * Value           - A pointer to the returned 32-bit value.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
byte HallTmr_GetCounterValue(HallTmr_TTimerValue *Value)
{
  *Value = getReg(TMRA0_CNTR);         /* Get lower part */
  *Value += ((dword)getReg(TMRA1_HOLD) << 16); /* Add higher part */
  return ERR_OK;                       /* OK */
}

/*
** ===================================================================
**     Method      :  HallTmr_Init (component FreeCntr)
**
**     Description :
**         Initializes the associated peripheral(s) and the beans 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void HallTmr_Init(void)
{
  /* TMRA0_CTRL: CM=0,PCS=0,SCS=0,ONCE=0,LENGTH=0,DIR=0,Co_INIT=0,OM=0 */
  setReg(TMRA0_CTRL,0x00);             /* Stop all functions of the timer */
  /* TMRA1_CTRL: CM=7,PCS=4,SCS=0,ONCE=0,LENGTH=0,DIR=0,Co_INIT=0,OM=0 */
  setReg(TMRA1_CTRL,0xE800);           /* Set up cascade counter mode */
  setReg(TMRA1_CNTR,0x00);             /* Reset counter register */
  setReg(TMRA0_CNTR,0x00);
  setReg(TMRA1_LOAD,0x00);             /* Reset load register */
  setReg(TMRA0_LOAD,0x00);
  setReg(TMRA0_COMP1,0xFFFF);          /* Set up compare 1 register to maximum */
  SetPV((byte)0x08);                   /* Set prescaler register according to the selected high speed CPU mode */
  setRegBitGroup(TMRA0_CTRL,CM,0x01);  /* Run counter */
}

/* END HallTmr. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.00 [04.35]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
